### ISSUE TITLE
Allow using multiple FDB instances with different FDB_HOME/FDB_CONFIG_FILE

### ISSUE THREAD

**Issue by geier1993** [ecmwf/pyfdb#17]
### Is your feature request related to a problem? Please describe.

We intend to use pyfdb to compare two local fdb.

Currently the python `FDB` object and the fdb c api only allow creating a "default" handle which will evaluate environmentvariables like `FDB_HOME` to relate to a specific fdb.

As a result, to list and query two different fdb, we have to do the following:

```
initialFdbHome = os.environ["FDB_HOME"]

os.environ["FDB_HOME"] = "path of first fdb"
fdb1 = pyfdb.FDB()

os.environ["FDB_HOME"] = "path of second fdb"
fdb2 = pyfdb.FDB()

os.environ["FDB_HOME"] = initalFdbHome
```

Alternatively the environment variable "FDB5_CONFIG_FILE" pointing to the config file ($FDB_HOME/etc/fdb/config.yaml) can be passed.

The request is realted to #12 with the difference that supporting customized paths is easier than allow passing a whole configuration object directly.

### Describe the solution you'd like

I would prefer to have configuration options on the `FDB` object, e.g.:

```
fdb1 = pyfdb.FDB(config_path="path to first fdb config file")
fdb2 = pyfgdb.FDB(config_path="path to second fdb config file")
```

This would require extending the C api by a call `fdb_new_handle_from_config_path` (or similar) that accepts a C string to the desired fdb config file.

Behind the C Interface `Config::make` can be used directly to create a `Config` that constructs `FDB`.

In addition, we could allow passing `fdb_home`:

```
fdb1 = pyfdb.FDB(fdb_home="path to first fdb home")
```

This would require creating a `Config` from a `LocalConfiguration` with the key `fdb_home`.  The config can be expanded and will then return a new `Config` with the loaded configuration file. ?

### Organisation

ECMWF

**Comment by tlmquintino** [comment]
indeed this is something we have been wanting to do for a while now. welcome improvement!

**Comment by tbkr** [comment]
This has been implemented by https://github.com/ecmwf/pyfdb/pull/25 imho. If any functionality is missing, feel free to reach out.
