### ISSUE TITLE
pyfdb should not depend on tox

### ISSUE THREAD

**Issue by juntyr** [ecmwf/pyfdb#39]
### What happened?

tox is a dev-dependency, not a dependency. Right now, installing pyfdb requires installing tox, which can result in version conflicts.

tox should be moved into an optional dependency, e.g. the test one.

### What are the steps to reproduce the bug?

N/A

### Version

v0.1.0

### Platform (OS and architecture)

N/A

### Organisation

University of Helsinki

**Comment by juntyr** [comment]
I'd really appreciate if a minor release with this issue fixed could be released in the next few days.

cc @SF-N

**Comment by tbkr** [comment]
Hey @juntyr,

sorry for the late response. I just pushed a version without the tox dependency to pypi. The newest version is no 0.1.1. You can find it in the optional dependencies called "dev" in case you need it.

Let me know, if you run into other issues. I'd close the issue for now.

Happy holidays in every case :)

**Comment by juntyr** [comment]
Thank you @tbkr for fixing the issue so quickly, everything works now :)

Happy holidays to you as well!
